name: Feature Request
description: Suggest something new
title: 'feat: '
labels: ['triage']
body:
  - type: markdown
    attributes:
      value: |
        ## Important Notes
        ### Before submitting
        Please check the [Issues](https://github.com/tink3rlabs/magic/issues) or [Discussions](https://github.com/tink3rlabs/magic/discussions) to see if a similar request has been posted.

        ### Contributing
        If you encounter an issue, we highly encourage you to submit a pull request or fork the project.

  - type: checkboxes
    id: existing-issue
    attributes:
      label: Check Existing Issues
      description: Please confirm that you've checked for existing similar requests
      options:
        - label: I have searched the existing issues and discussions.
          required: true
  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please provide a clear and concise description of what the problem is.
      placeholder: "Ex. I'm always frustrated when..."
    validations:
      required: true
  - type: textarea
    id: solution-description
    attributes:
      label: Desired Solution you'd like
      description: Clearly describe what you want to happen.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.

