name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: 'Auto-assign issue or pull request'
      uses: pozil/auto-assign-issue@v2.1.2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        assignees: ${{ github.event.pull_request.user.login || github.event.issue.user.login }},Lutherwaves
        numOfAssignee: 2

