name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  conventional-commits:
    name: Conventional Commits Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
     - name: Conventional Commits
       uses: webiny/action-conventional-commits@7f91b1595ca1951cdb671ddc9f07a49081ec5b69 # v1.4.2
       with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         allowed-commit-types: "feat,fix,cicd,chore,patch,release,test,docs,refactor,ci,dev,test"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: conventional-commits
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1
          persist-credentials: false
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: '1.25.3'
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.12.2
          args: --timeout=5m
          skip-cache: true
          skip-save-cache: true
        env:
          GOPROXY: https://proxy.golang.org,direct
  
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    timeout-minutes: 10
    # services:
    #   cassandra:
    #     image: cassandra:5 # Use a specific version if needed
    #     ports:
    #       - 9042:9042
    #     options: >-
    #       --hostname cassandra
    #       --health-cmd "cqlsh --debug -e 'DESCRIBE KEYSPACES' || exit 1"
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 7
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1
          persist-credentials: false
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: '1.25.3'
          cache: true
      - name: Run tests
        run: go test -v -cover ./...
        # env:
        #   CASSANDRA_HOSTS: "localhost"
        #   CASSANDRA_KEYSPACE: "testkeyspace"

